# generated by datamodel-codegen:
#   filename:  Schema.json
#   timestamp: 2024-07-19T13:28:01+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import ConfigDict, Field, conint
from pydantic_settings import BaseSettings


class LogLevel(Enum):
    INFO = 'INFO'
    DEBUG = 'DEBUG'
    WARNING = 'WARNING'
    ERROR = 'ERROR'


class Chromadb(BaseSettings):
    model_config = ConfigDict(
        extra='forbid',
    )
    host: Optional[str] = None
    port: Optional[conint(ge=0, le=65535)] = None


class Application(BaseSettings):
    model_config = ConfigDict(
        extra='forbid',
    )
    port: Optional[conint(ge=0, le=65535)] = None
    logLevel: Optional[LogLevel] = None
    chromadb: Optional[Chromadb] = Field(None, title='ChromaDBConfig')
